import Head from 'next/head';
import Nav from '@/components/NavBar';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jensen.Dev.Data-Mining</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gvsu.png" />
      </Head>

      <div className="relative">
        <Nav />
        <div className="flex flex-col items-center justify-center pt-16 max-w-screen-lg w-full mx-auto">
          <Image
            src="/pairplotirisEDA.png"
            alt="pair plot exploratory data analysis of iris penguin data set"
            height={400}
            width={400}
          />
        </div>
      </div>
    </>
  )
}
