import Head from 'next/head';
import Nav from '@/components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Jensen.Dev.Data-Mining</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gvsu.png" />
      </Head>
      <Nav />
    </>
  )
}
