import Head from 'next/head';
import NavBar from '@/components/NavBar';
import NeuralNetworkForm from '@/components/NeuralNetwork/NeuralNetworkForm';

export default function NeuralNetwork() {
    return (
        <>
            <Head>
                <title>Jensen: Data-Miner;</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/gvsu.png" />
            </Head>
            <div className="relative">
                <NavBar />
            </div>
            <div className="pt-1/6">
                <div className="flex flex-col items-center justify-center h-screen">
                    <NeuralNetworkForm />
                </div>
            </div>
        </>
    )
}
